datasources:
    default:
        url: jdbc:h2:mem:default;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password: ''
        schema-generate: CREATE_DROP
        dialect: H2
micronaut:
    application:
        name: pÃªu accounting
